services:

  directory-lister:
    image: directorylister/directorylister:<version>
    environment:
      APP_LANGUAGE: id
      DISPLAY_READMES: true
      READMES_FIRST: false
      # ZIP_DOWNLOADS: true
      TIMEZONE: Asia/Jakarta
      # See configuration docs for additional variables
    ports:
      - 80:80
    volumes:
      - ./data:/data
    restart: unless-stopped
